Repository hazelcast/hazelcast-python-client, pull requests merged in 2018-11, with the labels that each got.

#125 categorize mutual authetincation tests
  tests/ssl/mutual_authentication_test.py
Labels: Type: Test-Failure

#129 Readme update
  README.md
  README.rst
  docs/api/index.rst
  docs/configuration.rst
  docs/data_structures.rst
  docs/distributed_events.rst
  docs/getting_started.rst
  docs/hazelcast.client.rst
  docs/hazelcast.cluster.rst
  docs/hazelcast.config.rst
  docs/hazelcast.connection.rst
  docs/hazelcast.core.rst
  docs/hazelcast.discovery.rst
  docs/hazelcast.exception.rst
  docs/hazelcast.future.rst
  docs/hazelcast.hash.rst
  docs/hazelcast.invocation.rst
  docs/hazelcast.lifecycle.rst
  docs/hazelcast.near_cache.rst
  docs/hazelcast.partition.rst
  docs/hazelcast.proxy.atomic_long.rst
  docs/hazelcast.proxy.atomic_reference.rst
  docs/hazelcast.proxy.base.rst
  docs/hazelcast.proxy.count_down_latch.rst
  docs/hazelcast.proxy.executor.rst
  docs/hazelcast.proxy.id_generator.rst
  docs/hazelcast.proxy.list.rst
  docs/hazelcast.proxy.lock.rst
  docs/hazelcast.proxy.map.rst
  docs/hazelcast.proxy.multi_map.rst
  docs/hazelcast.proxy.queue.rst
  docs/hazelcast.proxy.replicated_map.rst
  docs/hazelcast.proxy.ringbuffer.rst
  docs/hazelcast.proxy.rst
  docs/hazelcast.proxy.semaphore.rst
  docs/hazelcast.proxy.set.rst
  docs/hazelcast.proxy.topic.rst
  docs/hazelcast.proxy.transactional_list.rst
  docs/hazelcast.proxy.transactional_map.rst
  docs/hazelcast.proxy.transactional_multi_map.rst
  docs/hazelcast.proxy.transactional_queue.rst
  docs/hazelcast.proxy.transactional_set.rst
  docs/hazelcast.reactor.rst
  docs/hazelcast.rst
  docs/hazelcast.serialization.api.rst
  docs/hazelcast.serialization.data.rst
  docs/hazelcast.serialization.rst
  docs/hazelcast.transaction.rst
  docs/hazelcast.util.rst
  docs/index.rst
  docs/serialization.rst
  examples/README.md
  setup.py
Labels: Type: Documentation

#131 Update org-website examples
  examples/org-website/atomic_long_sample.py
  examples/org-website/custom_serializer_sample.py
  examples/org-website/entry_processor_sample.py
  examples/org-website/executor_service_sample.py
  examples/org-website/global_serializer_sample.py
  examples/org-website/identified_data_serializable_sample.py
  examples/org-website/list_sample.py
  examples/org-website/lock_sample.py
  examples/org-website/map_sample.py
  examples/org-website/multimap_sample.py
  examples/org-website/portable_serializable_sample.py
  examples/org-website/query_sample.py
  examples/org-website/queue_sample.py
  examples/org-website/replicated_map_sample.py
  examples/org-website/ringbuffer_sample.py
  examples/org-website/set_sample.py
  examples/org-website/topic_sample.py
Labels: Type: Cleanup

#132 Update the member tool documentation
  README.md
Labels: Type: Documentation

#133 Retouches for current content.
  README.md
Labels: Type: Documentation

#134 Update readme
  README.md
Labels: Type: Documentation
