Repository hazelcast/hazelcast-python-client, pull requests merged in 2021-08, with the labels that each got.

#441 [API-537] Add support for the binary metrics
  docs/using_python_client_with_hazelcast_imdg.rst
  hazelcast/metrics.py
  hazelcast/statistics.py
  requirements-test.txt
  tests/integration/backward_compatible/statistics_test.py
  tests/unit/metrics/README.md
  tests/unit/metrics/__init__.py
  tests/unit/metrics/metrics.compatibility.binary
  tests/unit/metrics/metrics_test.py
Labels: Type: Enhancement, Type: Cleanup, Source: Internal

#444 Fix map tests for backward compatibility
  tests/integration/backward_compatible/proxy/map_test.py
Labels: Type: Test-Failure, Source: Internal

#450 Improve test runner
  .gitignore
  run_tests.py
Labels: Type: Enhancement, Source: Internal

#445 Follow-up aggregators implementation
  docs/api/aggregator.rst
  docs/api/modules.rst
  docs/features.rst
  docs/using_python_client_with_hazelcast_imdg.rst
  examples/aggregators/aggregators_example.py
  hazelcast/aggregator.py
  hazelcast/core.py
  hazelcast/serialization/objects.py
  hazelcast/serialization/service.py
  tests/integration/backward_compatible/proxy/map_test.py
Labels: Type: Enhancement, Type: Cleanup, Source: Internal

#449 Make Address readable via IdentifiedDataSerializer
  hazelcast/serialization/objects.py
  hazelcast/serialization/service.py
  tests/integration/backward_compatible/proxy/reliable_topic_test.py
Labels: Type: Defect, Source: Internal

#452 Fix minor problems with the new security module
  docs/api/modules.rst
  docs/api/security.rst
  docs/securing_client_connection.rst
  hazelcast/client.py
  hazelcast/security.py
  hazelcast/security/__init__.py
  tests/unit/token_provider_test.py
Labels: Type: Cleanup, Source: Internal

#451 Projections added to python client
  docs/using_python_client_with_hazelcast_imdg.rst
  hazelcast/core.py
  hazelcast/projection.py
  hazelcast/protocol/codec/map_project_codec.py
  hazelcast/protocol/codec/map_project_with_predicate_codec.py
  hazelcast/proxy/map.py
  hazelcast/serialization/serialization_const.py
  hazelcast/serialization/serializer.py
  hazelcast/serialization/service.py
  tests/integration/backward_compatible/proxy/map_test.py
Labels: Type: Enhancement, Source: Community

#453 Add documentation for the Kerberos authentication
  docs/securing_client_connection.rst
Labels: Type: Documentation, Source: Internal

#454 Projections follow up
  docs/api/modules.rst
  docs/api/projection.rst
  docs/features.rst
  docs/using_python_client_with_hazelcast_imdg.rst
  examples/projections/projections_example.py
  hazelcast/core.py
  hazelcast/projection.py
  hazelcast/proxy/map.py
  tests/integration/backward_compatible/proxy/map_test.py
  tests/unit/projection_test.py
Labels: Type: Cleanup, Source: Internal

#455 Token providers can use the member address for token creation
  docs/securing_client_connection.rst
  hazelcast/connection.py
  hazelcast/security.py
Labels: Source: Internal

#456 [API-700] v5 SQL: Initial PR
  docs/conf.py
  docs/using_python_client_with_hazelcast_imdg.rst
  hazelcast/__init__.py
  hazelcast/protocol/builtin.py
  hazelcast/sql.py
  start_rc.py
  tests/base.py
  tests/integration/backward_compatible/proxy/distributed_objects_test.py
  tests/integration/backward_compatible/sql_test.py
Labels: Type: Enhancement, Type: Documentation, Type: Cleanup, Source: Internal

#457 [API-701] v5 SQL: Use different logic for getting query connections
  hazelcast/connection.py
  hazelcast/sql.py
  hazelcast/util.py
  requirements-dev.txt
  tests/integration/backward_compatible/authentication_tests/authentication_test.py
  tests/integration/backward_compatible/cluster_test.py
  tests/integration/backward_compatible/proxy/cp/atomic_long_test.py
  tests/integration/backward_compatible/proxy/cp/atomic_reference_test.py
  tests/integration/backward_compatible/proxy/map_test.py
  tests/integration/backward_compatible/proxy/reliable_topic_test.py
  tests/integration/backward_compatible/proxy/ringbuffer_test.py
  tests/integration/backward_compatible/sql_test.py
  tests/integration/backward_compatible/statistics_test.py
  tests/unit/sql_test.py
  tests/util.py
Labels: Type: Enhancement, Type: Cleanup, Source: Internal

#458 [API-702] v5 SQL: Remove unused load balancer methods
  hazelcast/util.py
  tests/integration/backward_compatible/sql_test.py
  tests/unit/load_balancer_test.py
Labels: Type: Cleanup, Source: Internal

#459 [API-703] v5 SQL: Add default serializers for the new types
  docs/serialization.rst
  hazelcast/serialization/serialization_const.py
  hazelcast/serialization/serializer.py
  hazelcast/serialization/service.py
  hazelcast/util.py
  tests/integration/backward_compatible/serialization/serializers_test.py
  tests/integration/backward_compatible/sql_test.py
  tests/unit/serialization/binary_compatibility/1.serialization.compatibility.binary
  tests/unit/serialization/binary_compatibility/README.md
  tests/unit/serialization/binary_compatibility/reference_objects.py
  tests/unit/serialization/serializers_test.py
  tests/unit/util_test.py
Labels: Type: Enhancement, Source: Internal
