Repository hazelcast/hazelcast-python-client, pull requests merged in 2021-07, with the labels that each got.

#430 Clean up comment. Word 'access' used twice consecutively.
  hazelcast/client.py
Labels: Source: Community

#432 Check the enterprise key properly in the test runner
  run_tests.py
Labels: Source: Internal, Type: Defect

#431 Make the HazelcastInstanceNotActiveError non-retryable
  hazelcast/errors.py
Labels: Source: Internal, Type: Defect

#435 Update Hazelcast version used in tests
  start_rc.py
Labels: Source: Internal

#436 Fix frame reader
  hazelcast/connection.py
  tests/integration/backward_compatible/proxy/map_test.py
Labels: Source: Community, Type: Critical, Type: Defect

#438 Mark the client version as 4.2.1 for the next development cycle
  docs/conf.py
  hazelcast/__init__.py
  tests/integration/backward_compatible/proxy/map_test.py
Labels: Source: Internal
