Repository hazelcast/hazelcast-python-client, pull requests merged in 2021-02, with the labels that each got.

#347 Do not check backup timeout for resolved invocations
  hazelcast/invocation.py
Labels: Source: Internal, Type: Cleanup

#348 [4.0.z] Do not check backup timeout for resolved invocations
  hazelcast/invocation.py
Labels: Source: Internal, Type: Cleanup

#344 Cleanup resources when the connection attempt fails immediately
  hazelcast/reactor.py
  tests/reactor_test.py
Labels: Source: Internal, Type: Defect

#343 Cleanup resources when the connection attempt fails immediately
  hazelcast/reactor.py
  tests/reactor_test.py
Labels: Source: Internal, Type: Defect

#346 Set the cluster connection timeout to infinite by default
  docs/client_connection_strategy.rst
  hazelcast/client.py
  hazelcast/config.py
  hazelcast/connection.py
  hazelcast/cp.py
  hazelcast/listener.py
  tests/config_test.py
  tests/connection_strategy_test.py
Labels: Source: Internal, Type: Documentation, Type: Enhancement

#345 Replace utf with string in public API
  docs/serialization.rst
  docs/using_python_client_with_hazelcast_imdg.rst
  examples/map/map_portable_query_example.py
  examples/map/map_portable_versioning_example.py
  examples/org-website/custom_serializer_sample.py
  examples/org-website/executor_service_sample.py
  examples/org-website/identified_data_serializable_sample.py
  examples/org-website/portable_serializable_sample.py
  examples/org-website/query_sample.py
  examples/serialization/global_serialization_example.py
  examples/serialization/identified_data_serializable_example.py
  examples/serialization/portable_example.py
  hazelcast/predicate.py
  hazelcast/serialization/api.py
  hazelcast/serialization/input.py
  hazelcast/serialization/output.py
  hazelcast/serialization/portable/classdef.py
  hazelcast/serialization/portable/reader.py
  hazelcast/serialization/portable/writer.py
  hazelcast/serialization/serializer.py
  tests/predicate_test.py
  tests/proxy/cp/atomic_reference_test.py
  tests/proxy/executor_test.py
  tests/proxy/map_test.py
  tests/serialization/binary_compatibility/reference_objects.py
  tests/serialization/custom_global_serialization_test.py
  tests/serialization/identified_test.py
  tests/serialization/morphing_portable_test.py
  tests/serialization/portable_test.py
  tests/soak_test/map_soak_test.py
Labels: Source: Internal, Type: Enhancement

#369 [4.0.z] Do not overwrite invocation timeout in the constructor
  hazelcast/invocation.py
  tests/invocation_test.py
Labels: Source: Internal, Type: Defect

#368 Do not overwrite invocation timeout in the constructor
  hazelcast/invocation.py
  tests/invocation_test.py
Labels: Source: Internal, Type: Defect

#370 Use time.monotonic() instead of time.time() for profiling
  tests/base.py
  tests/client_test.py
  tests/proxy/cp/count_down_latch_test.py
  tests/proxy/cp/semaphore_test.py
  tests/reactor_test.py
  tests/soak_test/map_soak_test.py
  tests/statistics_test.py
  tests/util.py
Labels: Source: Community, Type: Enhancement
