Repository hazelcast/hazelcast-python-client, pull requests merged in 2022-12, with the labels that each got.

#592 [API-1014] Correct the FieldType values for Portable.
  hazelcast/serialization/portable/classdef.py
  tests/unit/serialization/binary_compatibility/1.serialization.compatibility.binary
  tests/unit/serialization/binary_compatibility/README.md
  tests/unit/serialization/binary_compatibility/reference_objects.py
Labels: Type: Defect, Type: Critical, Estimation: S, Source: Internal

#600 Add put_all() to MultiMap [API-1235]
  hazelcast/protocol/builtin.py
  hazelcast/protocol/codec/multi_map_put_all_codec.py
  hazelcast/proxy/multi_map.py
  tests/integration/backward_compatible/proxy/multi_map_test.py
  tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
Labels: Type: Enhancement, Source: Community

#521 Convert `Config` classes to public API [API-1280]
  docs/api/modules.rst
  docs/config.rst
  docs/configuration_overview.rst
  docs/index.rst
  examples/configuration/kwargs_configuration_example.py
  examples/configuration/object_configuration_example.py
  hazelcast/client.py
  hazelcast/config.py
  hazelcast/proxy/flake_id_generator.py
  hazelcast/proxy/reliable_topic.py
  hazelcast/reactor.py
  hazelcast/serialization/service.py
  tests/integration/backward_compatible/client_test.py
  tests/unit/config_test.py
  tests/unit/invocation_test.py
  tests/unit/near_cache_test.py
  tests/unit/reactor_test.py
  tests/unit/serialization/binary_compatibility/binary_compatibility_test.py
  tests/unit/serialization/compact_test.py
  tests/unit/serialization/custom_global_serialization_test.py
  tests/unit/serialization/identified_test.py
  tests/unit/serialization/int_serialization_test.py
  tests/unit/serialization/morphing_portable_test.py
  tests/unit/serialization/portable_test.py
  tests/unit/serialization/serialization_test.py
  tests/unit/serialization/serializers_test.py
  tests/unit/serialization/string_test.py
Labels: Type: Enhancement, Source: Internal
