Repository hazelcast/hazelcast-python-client, pull requests merged in 2022-10, with the labels that each got.

#584 Make map#remove_all tests backward compatibility aware
  docs/conf.py
  hazelcast/__init__.py
  tests/integration/backward_compatible/proxy/map_nearcache_test.py
  tests/integration/backward_compatible/proxy/map_test.py
  tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
Labels: Type: Defect, Source: Internal

#583 Fix Jupyter notebook bugs. [API-1508]
  examples/jupyter-notebooks/Hazelcast Python Client SQL Support with Hazelcast Viridian Notebook.ipynb
Labels: Type: Enhancement, Source: Internal

#574 Nested compact field's serializer can be None if it is not registered [API-1416]
  hazelcast/serialization/compact.py
  tests/unit/serialization/compact_test.py
Labels: Type: Defect, Priority: Low, Estimation: S, Source: Internal

#569 Add Missing Portable Read/Write Functions [API-1014]
  hazelcast/serialization/api.py
  hazelcast/serialization/portable/classdef.py
  hazelcast/serialization/portable/reader.py
  hazelcast/serialization/portable/writer.py
  tests/unit/serialization/morphing_portable_test.py
  tests/unit/serialization/portable_test.py
Labels: Type: Enhancement, Priority: Low, Estimation: L, Source: Internal

#570 publish_all() method for Topic [API-1529]
  examples/topic/topic_example.py
  hazelcast/protocol/codec/topic_publish_all_codec.py
  hazelcast/proxy/topic.py
  tests/integration/backward_compatible/proxy/topic_test.py
  tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
Labels: Type: Enhancement, Priority: Low, Estimation: S, Source: Internal
