Repository hazelcast/hazelcast-python-client, pull requests merged in 2023-03, with the labels that each got.

#610 Introduce various updates for the Compact serialization [API-1564]
  hazelcast/serialization/compact.py
  hazelcast/serialization/service.py
  tests/unit/serialization/compact_test.py
Labels: Type: Enhancement, Type: Cleanup, Source: Internal

#611 Update Compact documentation [API-1564]
  docs/serialization.rst
  hazelcast/serialization/api.py
Labels: Type: Documentation, Source: Internal

#613 Send client state to cluster in reconnections [API-1564]
  hazelcast/connection.py
  tests/integration/backward_compatible/serialization/compact_test.py
  tests/integration/connection_manager_test.py
Labels: Source: Internal

#612 Do not allow different item types while writing Compact arrays [API-1564]
  hazelcast/serialization/api.py
  hazelcast/serialization/compact.py
  tests/unit/serialization/compact_test.py
Labels: Source: Internal

#618 Eagerly deserialize responses consisting of list of data [API-1964]
  docs/serialization.rst
  hazelcast/proxy/list.py
  hazelcast/proxy/map.py
  hazelcast/proxy/multi_map.py
  hazelcast/proxy/queue.py
  hazelcast/proxy/reliable_topic.py
  hazelcast/proxy/replicated_map.py
  hazelcast/proxy/ringbuffer.py
  hazelcast/proxy/set.py
  hazelcast/proxy/transactional_map.py
  hazelcast/proxy/transactional_multi_map.py
  hazelcast/serialization/objects.py
  hazelcast/serialization/service.py
  hazelcast/util.py
  tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
Labels: Source: Internal

#615 Make sure the Compact schema is replicated on all known cluster members [API-1564]
  .coveragerc
  hazelcast/client.py
  hazelcast/compact.py
  hazelcast/protocol/builtin.py
  hazelcast/protocol/codec/client_send_schema_codec.py
  hazelcast/protocol/codec/custom/field_descriptor_codec.py
  hazelcast/protocol/codec/custom/schema_codec.py
  hazelcast/serialization/compact.py
  tests/integration/compact_test.py
  tests/unit/client_message_test.py
  tests/unit/serialization/compact_test.py
Labels: Type: Defect, Source: Internal

#619 Eagerly deserialize SQL columns of type OBJECT [API-1964]
  docs/serialization.rst
  hazelcast/protocol/builtin.py
  hazelcast/protocol/codec/sql_execute_codec.py
  hazelcast/protocol/codec/sql_fetch_codec.py
  hazelcast/serialization/portable/serializer.py
  hazelcast/sql.py
  tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
  tests/integration/backward_compatible/sql_test.py
Labels: Source: Internal

#620 Introduce minor fixes before 5.2.0
  README.rst
  docs/getting_started.rst
  examples/README.md
  examples/jupyter-notebooks/Hazelcast Python Client SQL Support with Hazelcast Viridian Notebook.ipynb
  examples/paging-predicate/member-with-comparator/pom.xml
  hazelcast/serialization/api.py
Labels: Type: Cleanup, Source: Internal

#621 Add server version check to topic publish_all tests
  tests/integration/backward_compatible/proxy/topic_test.py
Labels: Type: Test-Failure, Source: Internal

#603 Fix custom lookup serializer for class error [API-1669]
  hazelcast/serialization/service.py
  tests/unit/serialization/custom_global_serialization_test.py
Labels: Type: Defect, Source: Internal

#622 Use the Viridian name for cloud discovery documentations
  README.rst
  docs/features.rst
  docs/index.rst
  docs/setting_up_client_network.rst
  examples/jupyter-notebooks/Hazelcast Python Client SQL Support with Hazelcast Viridian Notebook.ipynb
  hazelcast/client.py
  hazelcast/discovery.py
Labels: Type: Documentation, Type: Cleanup, Source: Internal

#626 DBAPI Docs [API-1972]
  docs/api/db.rst
  docs/api/modules.rst
  docs/index.rst
  docs/sql.rst
  docs/using_python_client_with_hazelcast.rst
  examples/sql/dbapi_example.py
  hazelcast/db.py
Labels: Type: Documentation, Source: Internal
