Repository hazelcast/hazelcast-python-client, pull requests merged in 2024-01, with the labels that each got.

#656 Python 3.12 ssl no longer has the `ssl.wrap_socket` method causes `hazelcast_cloud_discovery_test` failure [API-2195]
  tests/unit/discovery/hazelcast_cloud_discovery_test.py
Labels: Type: Test-Failure

#655 Added the new on_cancel callback to ReliableMessageListener [API-2195]
  docs/using_python_client_with_hazelcast.rst
  examples/reliable-topic/reliable_topic_example.py
  hazelcast/proxy/reliable_topic.py
  tests/integration/backward_compatible/proxy/reliable_topic_test.py
Labels: Type: Enhancement

#661 Migrate GitHub actions from AdoptOpenJDK to Eclipse Temurin [HZ-4195]
  .github/workflows/coverage_runner.yml
  .github/workflows/nightly_runner.yml
Labels: Source: Internal
